/// Config preview panel using ScribeEditor in read-only mode.
///
/// Shows generated config content with syntax highlighting, copy, and
/// download buttons. Displays metadata header with type, environment,
/// version, and generation source.
library;

import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../models/registry_enums.dart';
import '../../models/registry_models.dart';
import '../../theme/colors.dart';
import '../scribe/scribe_editor.dart';
import 'config_type_selector.dart' show languageFor;

/// Config preview panel with ScribeEditor and action buttons.
///
/// Renders a header with config metadata, the generated content in a
/// read-only [ScribeEditor], and Copy / Download action buttons.
class ConfigPreviewPanel extends StatelessWidget {
  /// The config to preview. Null shows an empty state prompt.
  final ConfigTemplateResponse? config;

  /// Called when the user taps Copy.
  final VoidCallback? onCopy;

  /// Called when the user taps Download.
  final VoidCallback? onDownload;

  /// Called when the user taps Regenerate.
  final VoidCallback? onRegenerate;

  /// Creates a [ConfigPreviewPanel].
  const ConfigPreviewPanel({
    super.key,
    required this.config,
    this.onCopy,
    this.onDownload,
    this.onRegenerate,
  });

  @override
  Widget build(BuildContext context) {
    if (config == null) {
      return Container(
        height: 300,
        decoration: BoxDecoration(
          color: CodeOpsColors.surface,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: CodeOpsColors.border),
        ),
        child: const Center(
          child: Text(
            'Select a config type and click Generate',
            style: TextStyle(
              color: CodeOpsColors.textTertiary,
              fontSize: 14,
            ),
          ),
        ),
      );
    }

    final c = config!;
    final language = languageFor(c.templateType);

    return Container(
      decoration: BoxDecoration(
        color: CodeOpsColors.surface,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: CodeOpsColors.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Header
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
            child: Row(
              children: [
                Expanded(
                  child: Wrap(
                    spacing: 12,
                    crossAxisAlignment: WrapCrossAlignment.center,
                    children: [
                      Text(
                        c.templateType.displayName,
                        style: const TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: CodeOpsColors.textPrimary,
                        ),
                      ),
                      if (c.environment != null)
                        _Badge(label: c.environment!),
                      if (c.version != null)
                        _Badge(label: 'v${c.version}'),
                      if (c.isAutoGenerated == true)
                        const _Badge(
                          label: 'auto',
                          color: CodeOpsColors.secondary,
                        ),
                    ],
                  ),
                ),
                if (onRegenerate != null)
                  _ActionButton(
                    icon: Icons.refresh,
                    tooltip: 'Regenerate',
                    onPressed: onRegenerate!,
                  ),
                _ActionButton(
                  icon: Icons.copy,
                  tooltip: 'Copy to clipboard',
                  onPressed: () {
                    Clipboard.setData(
                      ClipboardData(text: c.contentText ?? ''),
                    );
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('Copied to clipboard'),
                        duration: Duration(seconds: 2),
                      ),
                    );
                    onCopy?.call();
                  },
                ),
                _ActionButton(
                  icon: Icons.download,
                  tooltip: 'Download file',
                  onPressed: () => _handleDownload(context),
                ),
              ],
            ),
          ),
          const Divider(height: 1, color: CodeOpsColors.border),
          // Editor
          SizedBox(
            height: 400,
            child: ScribeEditor(
              content: c.contentText ?? '',
              language: language,
              readOnly: true,
              showCodeFolding: true,
              showLineNumbers: true,
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _handleDownload(BuildContext context) async {
    final c = config;
    if (c == null) return;

    final fileName = _suggestedFileName(c);
    final result = await FilePicker.platform.saveFile(
      dialogTitle: 'Save config file',
      fileName: fileName,
    );
    if (result == null) return;

    final file = File(result);
    await file.writeAsString(c.contentText ?? '');

    if (context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Saved to ${file.path}'),
          duration: const Duration(seconds: 2),
        ),
      );
    }
    onDownload?.call();
  }

  String _suggestedFileName(ConfigTemplateResponse c) {
    return switch (c.templateType) {
      ConfigTemplateType.dockerCompose => 'docker-compose.yml',
      ConfigTemplateType.applicationYml => 'application.yml',
      ConfigTemplateType.applicationProperties => 'application.properties',
      ConfigTemplateType.envFile => '.env',
      ConfigTemplateType.terraformModule => 'main.tf',
      ConfigTemplateType.claudeCodeHeader => 'CLAUDE.md',
      ConfigTemplateType.conventionsMd => 'CONVENTIONS.md',
      ConfigTemplateType.nginxConf => 'nginx.conf',
      ConfigTemplateType.githubActions => 'ci.yml',
      ConfigTemplateType.dockerfile => 'Dockerfile',
      ConfigTemplateType.makefile => 'Makefile',
      ConfigTemplateType.readmeSection => 'README.md',
    };
  }
}

class _Badge extends StatelessWidget {
  final String label;
  final Color color;

  const _Badge({
    required this.label,
    this.color = CodeOpsColors.textTertiary,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(4),
      ),
      child: Text(
        label,
        style: TextStyle(fontSize: 11, color: color),
      ),
    );
  }
}

class _ActionButton extends StatelessWidget {
  final IconData icon;
  final String tooltip;
  final VoidCallback onPressed;

  const _ActionButton({
    required this.icon,
    required this.tooltip,
    required this.onPressed,
  });

  @override
  Widget build(BuildContext context) {
    return IconButton(
      icon: Icon(icon, size: 18),
      tooltip: tooltip,
      color: CodeOpsColors.textSecondary,
      hoverColor: CodeOpsColors.primary.withValues(alpha: 0.1),
      onPressed: onPressed,
      splashRadius: 18,
      constraints: const BoxConstraints(minWidth: 36, minHeight: 36),
    );
  }
}
