// Widget tests for ServiceProfileListPage.
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:codeops/models/fleet_enums.dart';
import 'package:codeops/models/fleet_models.dart';
import 'package:codeops/pages/fleet/service_profile_list_page.dart';
import 'package:codeops/providers/fleet_providers.dart' hide selectedTeamIdProvider;
import 'package:codeops/providers/team_providers.dart' show selectedTeamIdProvider;

void main() {
  const teamId = 'team-1';

  final profiles = [
    FleetServiceProfile(
      id: 'sp-1',
      serviceName: 'postgres',
      displayName: 'PostgreSQL',
      imageName: 'postgres',
      imageTag: '16',
      restartPolicy: RestartPolicy.always,
      isAutoGenerated: false,
      isEnabled: true,
      startOrder: 1,
      createdAt: DateTime(2026, 2, 27, 9, 0),
    ),
    FleetServiceProfile(
      id: 'sp-2',
      serviceName: 'redis',
      displayName: 'Redis Cache',
      imageName: 'redis',
      imageTag: '7-alpine',
      restartPolicy: RestartPolicy.unlessStopped,
      isAutoGenerated: true,
      isEnabled: false,
      startOrder: 2,
      createdAt: DateTime(2026, 2, 27, 10, 0),
    ),
  ];

  void useWideViewport(WidgetTester tester) {
    tester.view.physicalSize = const Size(1600, 900);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
  }

  Widget createWidget({
    String? selectedTeamId = teamId,
    List<FleetServiceProfile>? profileList,
    bool loading = false,
    bool error = false,
  }) {
    return ProviderScope(
      overrides: [
        selectedTeamIdProvider.overrideWith((ref) => selectedTeamId),
        fleetServiceProfilesProvider.overrideWith(
          (ref, tid) {
            if (loading) {
              return Completer<List<FleetServiceProfile>>().future;
            }
            if (error) {
              return Future<List<FleetServiceProfile>>.error('Server error');
            }
            return Future.value(profileList ?? profiles);
          },
        ),
      ],
      child: const MaterialApp(
        home: Scaffold(body: ServiceProfileListPage()),
      ),
    );
  }

  group('ServiceProfileListPage', () {
    testWidgets('renders page title', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('Service Profiles'), findsOneWidget);
    });

    testWidgets('renders profile count', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('(2)'), findsOneWidget);
    });

    testWidgets('renders service names in table', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('postgres'), findsOneWidget);
      expect(find.text('redis'), findsOneWidget);
    });

    testWidgets('renders display names in table', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('PostgreSQL'), findsOneWidget);
      expect(find.text('Redis Cache'), findsOneWidget);
    });

    testWidgets('renders image:tag in table', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('postgres:16'), findsOneWidget);
      expect(find.text('redis:7-alpine'), findsOneWidget);
    });

    testWidgets('renders loading state', (tester) async {
      await tester.pumpWidget(createWidget(loading: true));
      await tester.pump();

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
    });

    testWidgets('renders error state with retry', (tester) async {
      await tester.pumpWidget(createWidget(error: true));
      await tester.pumpAndSettle();

      expect(find.text('Something Went Wrong'), findsOneWidget);
      expect(find.text('Retry'), findsOneWidget);
    });

    testWidgets('renders no team selected state', (tester) async {
      await tester.pumpWidget(createWidget(selectedTeamId: null));
      await tester.pumpAndSettle();

      expect(find.text('No team selected'), findsOneWidget);
    });

    testWidgets('renders empty state', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget(profileList: []));
      await tester.pumpAndSettle();

      expect(find.text('No service profiles found'), findsOneWidget);
    });

    testWidgets('renders Create button', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('Create'), findsOneWidget);
    });

    testWidgets('renders Auto-Generate button', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('Auto-Generate'), findsOneWidget);
    });

    testWidgets('renders search field', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.byIcon(Icons.search), findsOneWidget);
    });

    testWidgets('renders enabled switches', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.byType(Switch), findsNWidgets(2));
    });

    testWidgets('renders table headers', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('Service Name'), findsOneWidget);
      expect(find.text('Display Name'), findsOneWidget);
      expect(find.text('Image'), findsOneWidget);
      expect(find.text('Restart'), findsOneWidget);
      expect(find.text('Actions'), findsOneWidget);
    });

    testWidgets('renders action buttons per row', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      // Play (start), visibility (view), delete per row => 6 total
      expect(find.byIcon(Icons.play_arrow), findsNWidgets(2));
      expect(find.byIcon(Icons.visibility), findsNWidgets(2));
      expect(find.byIcon(Icons.delete_outline), findsNWidgets(2));
    });

    testWidgets('search filters profiles', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      // Enter search query that matches only Redis
      await tester.enterText(find.byType(TextField), 'Redis');
      await tester.pumpAndSettle();

      expect(find.text('Redis Cache'), findsOneWidget);
      expect(find.text('PostgreSQL'), findsNothing);
    });
  });
}
