// Widget tests for ServiceProfileDetailPage.
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:codeops/models/fleet_enums.dart';
import 'package:codeops/models/fleet_models.dart';
import 'package:codeops/pages/fleet/service_profile_detail_page.dart';
import 'package:codeops/providers/fleet_providers.dart' hide selectedTeamIdProvider;
import 'package:codeops/providers/team_providers.dart' show selectedTeamIdProvider;

void main() {
  const teamId = 'team-1';
  const profileId = 'sp-1';

  final detail = FleetServiceProfileDetail(
    id: profileId,
    serviceName: 'postgres',
    displayName: 'PostgreSQL',
    description: 'Main database service',
    imageName: 'postgres',
    imageTag: '16',
    command: 'postgres -c shared_buffers=256MB',
    workingDir: '/var/lib/postgresql/data',
    envVarsJson: '{"POSTGRES_DB":"codeops"}',
    portsJson: '{"5432":"5432"}',
    healthCheckCommand: 'pg_isready',
    healthCheckIntervalSeconds: 30,
    healthCheckTimeoutSeconds: 5,
    healthCheckRetries: 3,
    restartPolicy: RestartPolicy.always,
    memoryLimitMb: 512,
    cpuLimit: 1.5,
    isAutoGenerated: false,
    isEnabled: true,
    startOrder: 1,
    teamId: teamId,
    volumes: [
      FleetVolumeMount(
        id: 'v1',
        hostPath: '/data/postgres',
        containerPath: '/var/lib/postgresql/data',
        volumeName: 'pg-data',
        isReadOnly: false,
      ),
    ],
    networks: [
      FleetNetworkConfig(
        id: 'n1',
        networkName: 'codeops-net',
        aliases: 'db,postgres',
        ipAddress: '172.18.0.5',
      ),
    ],
    createdAt: DateTime(2026, 2, 27, 9, 0),
    updatedAt: DateTime(2026, 2, 27, 10, 0),
  );

  final detailNoVolumesNetworks = FleetServiceProfileDetail(
    id: profileId,
    serviceName: 'redis',
    displayName: 'Redis',
    imageName: 'redis',
    imageTag: '7',
    isEnabled: false,
    teamId: teamId,
    volumes: [],
    networks: [],
    createdAt: DateTime(2026, 2, 27, 9, 0),
  );

  void useWideViewport(WidgetTester tester) {
    tester.view.physicalSize = const Size(1600, 900);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
  }

  Widget createWidget({
    String? selectedTeamId = teamId,
    FleetServiceProfileDetail? profileDetail,
    bool loadingDetail = false,
    bool errorDetail = false,
  }) {
    return ProviderScope(
      overrides: [
        selectedTeamIdProvider.overrideWith((ref) => selectedTeamId),
        fleetServiceProfileDetailProvider.overrideWith(
          (ref, params) {
            if (loadingDetail) {
              return Completer<FleetServiceProfileDetail>().future;
            }
            if (errorDetail) {
              return Future<FleetServiceProfileDetail>.error('Server error');
            }
            return Future.value(profileDetail ?? detail);
          },
        ),
      ],
      child: MaterialApp(
        home: Scaffold(
          body: ServiceProfileDetailPage(profileId: profileId),
        ),
      ),
    );
  }

  group('ServiceProfileDetailPage', () {
    testWidgets('renders profile name in header', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('PostgreSQL'), findsAtLeastNWidgets(1));
    });

    testWidgets('renders image:tag in header', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('postgres:16'), findsAtLeastNWidgets(1));
    });

    testWidgets('renders enabled badge', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('Enabled'), findsAtLeastNWidgets(1));
    });

    testWidgets('renders disabled badge for disabled profile', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(
          createWidget(profileDetail: detailNoVolumesNetworks));
      await tester.pumpAndSettle();

      expect(find.text('Disabled'), findsOneWidget);
    });

    testWidgets('renders all 3 tab labels', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(
          find.byWidgetPredicate(
              (w) => w is Tab && w.text == 'Configuration'),
          findsOneWidget);
      expect(
          find.byWidgetPredicate((w) => w is Tab && w.text == 'Volumes'),
          findsOneWidget);
      expect(
          find.byWidgetPredicate((w) => w is Tab && w.text == 'Networks'),
          findsOneWidget);
    });

    testWidgets('renders Edit and Delete buttons', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('Edit'), findsOneWidget);
      expect(find.text('Delete'), findsOneWidget);
    });

    testWidgets('renders loading state', (tester) async {
      await tester.pumpWidget(createWidget(loadingDetail: true));
      await tester.pump();

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
    });

    testWidgets('renders error state with retry', (tester) async {
      await tester.pumpWidget(createWidget(errorDetail: true));
      await tester.pumpAndSettle();

      expect(find.text('Something Went Wrong'), findsOneWidget);
      expect(find.text('Retry'), findsOneWidget);
    });

    testWidgets('renders no team selected state', (tester) async {
      await tester.pumpWidget(createWidget(selectedTeamId: null));
      await tester.pumpAndSettle();

      expect(find.text('No team selected'), findsOneWidget);
    });

    // ───── Configuration Tab ─────

    testWidgets('config tab shows service profile info', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('General'), findsOneWidget);
      expect(find.text('Health Check'), findsOneWidget);
      expect(find.text('Resource Limits'), findsOneWidget);
    });

    testWidgets('config tab shows command', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      expect(find.text('postgres -c shared_buffers=256MB'), findsOneWidget);
    });

    // ───── Volumes Tab ─────

    testWidgets('volumes tab shows volume mounts', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      await tester.tap(
          find.byWidgetPredicate((w) => w is Tab && w.text == 'Volumes'));
      await tester.pumpAndSettle();

      expect(find.text('Add Volume'), findsOneWidget);
      expect(find.text('/var/lib/postgresql/data'), findsOneWidget);
      expect(find.text('/data/postgres'), findsOneWidget);
    });

    testWidgets('volumes tab shows empty state when no volumes',
        (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(
          createWidget(profileDetail: detailNoVolumesNetworks));
      await tester.pumpAndSettle();

      await tester.tap(
          find.byWidgetPredicate((w) => w is Tab && w.text == 'Volumes'));
      await tester.pumpAndSettle();

      expect(find.text('No volume mounts configured'), findsOneWidget);
    });

    // ───── Networks Tab ─────

    testWidgets('networks tab shows network configs', (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(createWidget());
      await tester.pumpAndSettle();

      await tester.tap(
          find.byWidgetPredicate((w) => w is Tab && w.text == 'Networks'));
      await tester.pumpAndSettle();

      expect(find.text('Add Network'), findsOneWidget);
      expect(find.text('codeops-net'), findsOneWidget);
      expect(find.text('172.18.0.5'), findsOneWidget);
    });

    testWidgets('networks tab shows empty state when no networks',
        (tester) async {
      useWideViewport(tester);
      await tester.pumpWidget(
          createWidget(profileDetail: detailNoVolumesNetworks));
      await tester.pumpAndSettle();

      await tester.tap(
          find.byWidgetPredicate((w) => w is Tab && w.text == 'Networks'));
      await tester.pumpAndSettle();

      expect(find.text('No network configurations'), findsOneWidget);
    });
  });
}
