/// Dialog for auto-generating a service profile from a service registration.
///
/// Presents a text field for the service registration ID and calls
/// the auto-generate API on confirmation.
library;

import 'package:flutter/material.dart';

import '../../theme/colors.dart';

/// A dialog that collects a service registration ID for auto-generation.
///
/// Returns the service registration ID [String] when submitted,
/// or `null` if cancelled.
class AutoGenerateDialog extends StatefulWidget {
  /// Creates an [AutoGenerateDialog].
  const AutoGenerateDialog({super.key});

  /// Shows the dialog and returns the result.
  static Future<String?> show(BuildContext context) {
    return showDialog<String>(
      context: context,
      builder: (_) => const AutoGenerateDialog(),
    );
  }

  @override
  State<AutoGenerateDialog> createState() => _AutoGenerateDialogState();
}

class _AutoGenerateDialogState extends State<AutoGenerateDialog> {
  final _formKey = GlobalKey<FormState>();
  final _registrationIdCtrl = TextEditingController();

  @override
  void dispose() {
    _registrationIdCtrl.dispose();
    super.dispose();
  }

  /// Validates and submits the form.
  void _submit() {
    if (!_formKey.currentState!.validate()) return;
    Navigator.of(context).pop(_registrationIdCtrl.text.trim());
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: CodeOpsColors.surface,
      title: const Text('Auto-Generate Profile'),
      content: SizedBox(
        width: 400,
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Generate a service profile from an existing service '
                'registration in the Registry module.',
                style: TextStyle(color: CodeOpsColors.textSecondary),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _registrationIdCtrl,
                decoration: const InputDecoration(
                  labelText: 'Service Registration ID *',
                  hintText: 'UUID of the service registration',
                ),
                validator: (v) =>
                    (v == null || v.trim().isEmpty) ? 'Required' : null,
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text(
            'Cancel',
            style: TextStyle(color: CodeOpsColors.textSecondary),
          ),
        ),
        ElevatedButton(
          onPressed: _submit,
          child: const Text('Generate'),
        ),
      ],
    );
  }
}
