/// Configuration tab for the service profile detail page.
///
/// Displays all service profile metadata in a read-only card layout
/// including image, command, health check, resource limits, and
/// profile metadata fields.
library;

import 'package:flutter/material.dart';

import '../../models/fleet_models.dart';
import '../../theme/colors.dart';
import '../../theme/typography.dart';
import '../../utils/date_utils.dart';

/// Displays service profile configuration details in a read-only card.
class ServiceProfileConfigTab extends StatelessWidget {
  /// The service profile detail to display.
  final FleetServiceProfileDetail detail;

  /// Creates a [ServiceProfileConfigTab].
  const ServiceProfileConfigTab({super.key, required this.detail});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildSection('General', [
            _InfoRow(label: 'Service Name', value: detail.serviceName),
            _InfoRow(label: 'Display Name', value: detail.displayName),
            _InfoRow(label: 'Description', value: detail.description),
            _InfoRow(
              label: 'Image',
              value:
                  '${detail.imageName ?? ""}:${detail.imageTag ?? "latest"}',
            ),
            _InfoRow(label: 'Command', value: detail.command, mono: true),
            _InfoRow(label: 'Working Dir', value: detail.workingDir, mono: true),
            _InfoRow(
              label: 'Restart Policy',
              value: detail.restartPolicy?.displayName,
            ),
            _InfoRow(
              label: 'Start Order',
              value: detail.startOrder?.toString(),
            ),
            _InfoRow(
              label: 'Enabled',
              value: detail.isEnabled == true ? 'Yes' : 'No',
            ),
            _InfoRow(
              label: 'Auto-Generated',
              value: detail.isAutoGenerated == true ? 'Yes' : 'No',
            ),
          ]),
          const SizedBox(height: 24),
          _buildSection('Health Check', [
            _InfoRow(
              label: 'Command',
              value: detail.healthCheckCommand,
              mono: true,
            ),
            _InfoRow(
              label: 'Interval',
              value: detail.healthCheckIntervalSeconds != null
                  ? '${detail.healthCheckIntervalSeconds}s'
                  : null,
            ),
            _InfoRow(
              label: 'Timeout',
              value: detail.healthCheckTimeoutSeconds != null
                  ? '${detail.healthCheckTimeoutSeconds}s'
                  : null,
            ),
            _InfoRow(
              label: 'Retries',
              value: detail.healthCheckRetries?.toString(),
            ),
          ]),
          const SizedBox(height: 24),
          _buildSection('Resource Limits', [
            _InfoRow(
              label: 'Memory Limit',
              value: detail.memoryLimitMb != null
                  ? '${detail.memoryLimitMb} MB'
                  : null,
            ),
            _InfoRow(
              label: 'CPU Limit',
              value: detail.cpuLimit?.toStringAsFixed(2),
            ),
          ]),
          const SizedBox(height: 24),
          _buildSection('Environment & Ports', [
            _InfoRow(
              label: 'Env Vars',
              value: detail.envVarsJson,
              mono: true,
            ),
            _InfoRow(
              label: 'Ports',
              value: detail.portsJson,
              mono: true,
            ),
          ]),
          const SizedBox(height: 24),
          _buildSection('Metadata', [
            _InfoRow(
              label: 'Profile ID',
              value: detail.id,
              mono: true,
            ),
            _InfoRow(
              label: 'Service Registration',
              value: detail.serviceRegistrationId,
              mono: true,
            ),
            _InfoRow(
              label: 'Team ID',
              value: detail.teamId,
              mono: true,
            ),
            _InfoRow(
              label: 'Created',
              value: formatDateTime(detail.createdAt),
            ),
            _InfoRow(
              label: 'Updated',
              value: formatDateTime(detail.updatedAt),
            ),
          ]),
        ],
      ),
    );
  }

  /// Builds a titled section card.
  Widget _buildSection(String title, List<Widget> children) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: CodeOpsColors.surface,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: CodeOpsColors.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: CodeOpsTypography.titleMedium),
          const SizedBox(height: 16),
          ...children,
        ],
      ),
    );
  }
}

class _InfoRow extends StatelessWidget {
  final String label;
  final String? value;
  final bool mono;

  const _InfoRow({required this.label, this.value, this.mono = false});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 160,
            child: Text(
              label,
              style: CodeOpsTypography.bodySmall
                  .copyWith(color: CodeOpsColors.textTertiary),
            ),
          ),
          Expanded(
            child: Text(
              value ?? '\u2014',
              style: mono
                  ? CodeOpsTypography.code.copyWith(fontSize: 12)
                  : CodeOpsTypography.bodyMedium,
            ),
          ),
        ],
      ),
    );
  }
}
