// Tests for ConfigGeneratorPage.
//
// Verifies service mode default, service dropdown, config type chips,
// solution mode switch, solution dropdown, solution mode docker-compose
// restriction, generate button, generate all button, preview display,
// stored configs list, and empty state prompt.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:codeops/models/health_snapshot.dart';
import 'package:codeops/models/registry_enums.dart';
import 'package:codeops/models/registry_models.dart';
import 'package:codeops/pages/registry/config_generator_page.dart';
import 'package:codeops/providers/registry_providers.dart';

const _service1 = ServiceRegistrationResponse(
  id: 'svc-1',
  teamId: 'team-1',
  name: 'CodeOps Server',
  slug: 'codeops-server',
  serviceType: ServiceType.springBootApi,
  status: ServiceStatus.active,
);

const _solution1 = SolutionResponse(
  id: 'sol-1',
  teamId: 'team-1',
  name: 'CodeOps Platform',
  slug: 'codeops-platform',
  category: SolutionCategory.platform,
  status: SolutionStatus.active,
);

const _storedConfig = ConfigTemplateResponse(
  id: 'cfg-1',
  serviceId: 'svc-1',
  serviceName: 'CodeOps Server',
  templateType: ConfigTemplateType.dockerCompose,
  environment: 'dev',
  contentText: 'version: "3.8"',
  isAutoGenerated: true,
  version: 1,
);

PageResponse<ServiceRegistrationResponse> _servicePage(
    List<ServiceRegistrationResponse> items) {
  return PageResponse(
    content: items,
    page: 0,
    size: 20,
    totalElements: items.length,
    totalPages: 1,
    isLast: true,
  );
}

PageResponse<SolutionResponse> _solutionPage(List<SolutionResponse> items) {
  return PageResponse(
    content: items,
    page: 0,
    size: 20,
    totalElements: items.length,
    totalPages: 1,
    isLast: true,
  );
}

void _setWideViewport(WidgetTester tester) {
  tester.view.physicalSize = const Size(1600, 900);
  tester.view.devicePixelRatio = 1.0;
}

Widget _buildPage({List<Override> overrides = const []}) {
  return ProviderScope(
    overrides: overrides,
    child: const MaterialApp(
      home: Scaffold(body: ConfigGeneratorPage()),
    ),
  );
}

List<Override> _defaultOverrides({
  List<ConfigTemplateResponse> storedConfigs = const [],
}) {
  return [
    registryServicesProvider.overrideWith(
      (ref) async => _servicePage([_service1]),
    ),
    registrySolutionsProvider.overrideWith(
      (ref) async => _solutionPage([_solution1]),
    ),
    storedConfigsProvider.overrideWith(
      (ref) async => storedConfigs,
    ),
  ];
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('ConfigGeneratorPage', () {
    testWidgets('renders service mode by default', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      // Service radio is selected
      expect(find.text('Service'), findsOneWidget);
      expect(find.text('Solution'), findsOneWidget);
    });

    testWidgets('renders service dropdown', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      // Service dropdown hint is visible
      expect(find.text('Select Service'), findsOneWidget);
    });

    testWidgets('renders config type chips', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      expect(find.text('Docker Compose'), findsOneWidget);
      expect(find.text('Dockerfile'), findsOneWidget);
      expect(find.text('Makefile'), findsOneWidget);
    });

    testWidgets('generate selected button present', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      expect(find.text('Generate Selected'), findsOneWidget);
    });

    testWidgets('generate all button present in service mode', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      expect(find.text('Generate All'), findsOneWidget);
    });

    testWidgets('preview shows empty state prompt', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      expect(
        find.text('Select a config type and click Generate'),
        findsOneWidget,
      );
    });

    testWidgets('environment dropdown present', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      expect(find.text('Environment:'), findsOneWidget);
    });

    testWidgets('stored configs list renders', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(
        overrides: [
          registryServicesProvider.overrideWith(
            (ref) async => _servicePage([_service1]),
          ),
          registrySolutionsProvider.overrideWith(
            (ref) async => _solutionPage([_solution1]),
          ),
          storedConfigsProvider.overrideWith(
            (ref) async => [_storedConfig],
          ),
          configServiceIdProvider.overrideWith(
            (ref) => 'svc-1',
          ),
        ],
      ));
      await tester.pumpAndSettle();

      expect(find.text('Stored Configs'), findsOneWidget);
    });

    testWidgets('source selection card present', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      expect(find.text('Source Selection'), findsOneWidget);
    });

    testWidgets('config types card present', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPage(overrides: _defaultOverrides()));
      await tester.pumpAndSettle();

      expect(find.text('Config Types'), findsOneWidget);
    });
  });
}
