/// Service profile list page for the Fleet module.
///
/// Displays all service profiles for the current team in a sortable
/// data table at `/fleet/service-profiles`. Features include fuzzy search,
/// create/edit/delete, auto-generate from registry, start container,
/// and toggle enabled.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../models/fleet_models.dart';
import '../../providers/fleet_providers.dart' hide selectedTeamIdProvider;
import '../../providers/team_providers.dart' show selectedTeamIdProvider;
import '../../theme/colors.dart';
import '../../theme/typography.dart';
import '../../utils/fuzzy_matcher.dart';
import '../../widgets/fleet/auto_generate_dialog.dart';
import '../../widgets/fleet/service_profile_form.dart';
import '../../widgets/shared/confirm_dialog.dart';
import '../../widgets/shared/empty_state.dart';
import '../../widgets/shared/error_panel.dart';

/// The service profile list page at `/fleet/service-profiles`.
class ServiceProfileListPage extends ConsumerStatefulWidget {
  /// Creates a [ServiceProfileListPage].
  const ServiceProfileListPage({super.key});

  @override
  ConsumerState<ServiceProfileListPage> createState() =>
      _ServiceProfileListPageState();
}

class _ServiceProfileListPageState
    extends ConsumerState<ServiceProfileListPage> {
  String _searchQuery = '';
  bool _isBusy = false;

  /// Returns the currently selected team ID, or null.
  String? get _teamId => ref.read(selectedTeamIdProvider);

  /// Refreshes the service profile list.
  void _refresh() {
    final teamId = _teamId;
    if (teamId != null) {
      ref.invalidate(fleetServiceProfilesProvider);
    }
  }

  /// Applies fuzzy search to a profile by service name or display name.
  bool _matchesSearch(FleetServiceProfile p) {
    if (_searchQuery.isEmpty) return true;
    final name = p.displayName ?? p.serviceName ?? '';
    return FuzzyMatcher.match(_searchQuery, name).score > 0;
  }

  /// Opens the create service profile dialog.
  Future<void> _createProfile() async {
    final teamId = _teamId;
    if (teamId == null) return;

    final result = await ServiceProfileFormDialog.show(context);
    if (result == null || result is! CreateServiceProfileRequest) return;

    setState(() => _isBusy = true);
    try {
      final api = ref.read(fleetApiProvider);
      await api.createServiceProfile(teamId, result);
      _refresh();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Service profile created')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create profile: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  /// Opens the auto-generate dialog.
  Future<void> _autoGenerate() async {
    final teamId = _teamId;
    if (teamId == null) return;

    final registrationId = await AutoGenerateDialog.show(context);
    if (registrationId == null) return;

    setState(() => _isBusy = true);
    try {
      final api = ref.read(fleetApiProvider);
      await api.autoGenerateProfile(teamId, registrationId);
      _refresh();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Profile auto-generated')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to auto-generate: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  /// Deletes a service profile after confirmation.
  Future<void> _deleteProfile(FleetServiceProfile profile) async {
    final teamId = _teamId;
    if (teamId == null || profile.id == null) return;

    final confirmed = await showConfirmDialog(
      context,
      title: 'Delete Service Profile',
      message:
          'Delete "${profile.displayName ?? profile.serviceName}"? This cannot be undone.',
      confirmLabel: 'Delete',
      destructive: true,
    );
    if (confirmed != true) return;

    setState(() => _isBusy = true);
    try {
      final api = ref.read(fleetApiProvider);
      await api.deleteServiceProfile(teamId, profile.id!);
      _refresh();
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Service profile deleted')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to delete profile: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  /// Toggles the enabled state of a service profile.
  Future<void> _toggleEnabled(FleetServiceProfile profile) async {
    final teamId = _teamId;
    if (teamId == null || profile.id == null) return;

    setState(() => _isBusy = true);
    try {
      final api = ref.read(fleetApiProvider);
      await api.updateServiceProfile(
        teamId,
        profile.id!,
        UpdateServiceProfileRequest(
          isEnabled: !(profile.isEnabled ?? false),
        ),
      );
      _refresh();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to update profile: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  /// Starts a container from a service profile.
  Future<void> _startContainer(FleetServiceProfile profile) async {
    final teamId = _teamId;
    if (teamId == null || profile.id == null) return;

    setState(() => _isBusy = true);
    try {
      final api = ref.read(fleetApiProvider);
      await api.startContainer(
        teamId,
        StartContainerRequest(serviceProfileId: profile.id!),
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Container started')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to start container: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isBusy = false);
    }
  }

  /// Navigates to the service profile detail page.
  void _viewDetail(FleetServiceProfile profile) {
    if (profile.id != null) {
      context.go('/fleet/service-profiles/${profile.id}');
    }
  }

  @override
  Widget build(BuildContext context) {
    final teamId = ref.watch(selectedTeamIdProvider);

    if (teamId == null) {
      return const EmptyState(
        icon: Icons.group_outlined,
        title: 'No team selected',
        subtitle: 'Select a team to view service profiles.',
      );
    }

    final profilesAsync = ref.watch(fleetServiceProfilesProvider(teamId));

    return profilesAsync.when(
      loading: () => const Center(
        child: CircularProgressIndicator(color: CodeOpsColors.primary),
      ),
      error: (error, _) => ErrorPanel.fromException(
        error,
        onRetry: _refresh,
      ),
      data: (profiles) {
        final filtered = profiles.where(_matchesSearch).toList();

        return SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                children: [
                  Text(
                    'Service Profiles',
                    style: Theme.of(context).textTheme.headlineSmall,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    '(${filtered.length})',
                    style: const TextStyle(
                      color: CodeOpsColors.textSecondary,
                      fontSize: 16,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Toolbar
              _buildToolbar(),
              const SizedBox(height: 12),

              // Table or empty state
              if (filtered.isEmpty)
                const EmptyState(
                  icon: Icons.settings_applications_outlined,
                  title: 'No service profiles found',
                  subtitle:
                      'Create a profile or auto-generate from a service registration.',
                )
              else
                _buildTable(filtered),
            ],
          ),
        );
      },
    );
  }

  /// Builds the toolbar with search, create, auto-generate, and refresh.
  Widget _buildToolbar() {
    return Row(
      children: [
        // Search
        SizedBox(
          width: 280,
          child: TextField(
            decoration: InputDecoration(
              hintText: 'Search profiles...',
              prefixIcon: const Icon(Icons.search, size: 20),
              isDense: true,
              contentPadding:
                  const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
              border:
                  OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
            ),
            onChanged: (q) => setState(() => _searchQuery = q),
          ),
        ),
        const Spacer(),

        // Auto-Generate
        OutlinedButton.icon(
          onPressed: _isBusy ? null : _autoGenerate,
          icon: const Icon(Icons.auto_fix_high, size: 16),
          label: const Text('Auto-Generate'),
          style: OutlinedButton.styleFrom(
            foregroundColor: CodeOpsColors.secondary,
            side: const BorderSide(color: CodeOpsColors.secondary),
          ),
        ),
        const SizedBox(width: 8),

        // Create
        ElevatedButton.icon(
          onPressed: _isBusy ? null : _createProfile,
          icon: const Icon(Icons.add, size: 18),
          label: const Text('Create'),
        ),
        const SizedBox(width: 8),

        // Refresh
        IconButton(
          icon: const Icon(Icons.refresh, size: 20),
          color: CodeOpsColors.textSecondary,
          onPressed: _isBusy ? null : _refresh,
          tooltip: 'Refresh',
        ),
      ],
    );
  }

  /// Builds the service profiles data table.
  Widget _buildTable(List<FleetServiceProfile> profiles) {
    return Container(
      decoration: BoxDecoration(
        color: CodeOpsColors.surface,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: CodeOpsColors.border),
      ),
      child: Table(
        columnWidths: const {
          0: FlexColumnWidth(1.5), // Service Name
          1: FlexColumnWidth(1.5), // Display Name
          2: FlexColumnWidth(1.5), // Image
          3: FixedColumnWidth(100), // Restart
          4: FixedColumnWidth(60), // Auto
          5: FixedColumnWidth(60), // Enabled
          6: FixedColumnWidth(60), // Order
          7: FixedColumnWidth(140), // Actions
        },
        defaultVerticalAlignment: TableCellVerticalAlignment.middle,
        children: [
          // Header
          TableRow(
            decoration: BoxDecoration(
              color: CodeOpsColors.surfaceVariant,
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(8),
                topRight: Radius.circular(8),
              ),
            ),
            children: const [
              _HeaderCell('Service Name'),
              _HeaderCell('Display Name'),
              _HeaderCell('Image'),
              _HeaderCell('Restart'),
              _HeaderCell('Auto'),
              _HeaderCell('On'),
              _HeaderCell('Order'),
              _HeaderCell('Actions'),
            ],
          ),
          // Data rows
          ...profiles.map(_buildRow),
        ],
      ),
    );
  }

  /// Builds a single profile row.
  TableRow _buildRow(FleetServiceProfile profile) {
    return TableRow(
      decoration: BoxDecoration(
        border: Border(
          bottom:
              BorderSide(color: CodeOpsColors.border.withValues(alpha: 0.5)),
        ),
      ),
      children: [
        _DataCell(
          child: InkWell(
            onTap: () => _viewDetail(profile),
            child: Text(
              profile.serviceName ?? '\u2014',
              style: CodeOpsTypography.bodyMedium
                  .copyWith(color: CodeOpsColors.primary),
            ),
          ),
        ),
        _DataCell(text: profile.displayName ?? '\u2014'),
        _DataCell(
          text: '${profile.imageName ?? ""}:${profile.imageTag ?? "latest"}',
          mono: true,
        ),
        _DataCell(text: profile.restartPolicy?.displayName ?? '\u2014'),
        _DataCell(
          child: Icon(
            profile.isAutoGenerated == true
                ? Icons.auto_fix_high
                : Icons.edit,
            size: 16,
            color: profile.isAutoGenerated == true
                ? CodeOpsColors.secondary
                : CodeOpsColors.textTertiary,
          ),
        ),
        _DataCell(
          child: Switch(
            value: profile.isEnabled ?? false,
            onChanged: _isBusy ? null : (_) => _toggleEnabled(profile),
            materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
          ),
        ),
        _DataCell(text: '${profile.startOrder ?? "\u2014"}'),
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 4),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              IconButton(
                icon: const Icon(Icons.play_arrow, size: 16),
                color: CodeOpsColors.success,
                onPressed: _isBusy ? null : () => _startContainer(profile),
                tooltip: 'Start Container',
                constraints:
                    const BoxConstraints(minWidth: 28, minHeight: 28),
                padding: EdgeInsets.zero,
                style: IconButton.styleFrom(
                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
              ),
              IconButton(
                icon: const Icon(Icons.visibility, size: 16),
                color: CodeOpsColors.textSecondary,
                onPressed: () => _viewDetail(profile),
                tooltip: 'View Details',
                constraints:
                    const BoxConstraints(minWidth: 28, minHeight: 28),
                padding: EdgeInsets.zero,
                style: IconButton.styleFrom(
                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
              ),
              IconButton(
                icon: const Icon(Icons.delete_outline, size: 16),
                color: CodeOpsColors.error,
                onPressed: _isBusy ? null : () => _deleteProfile(profile),
                tooltip: 'Delete',
                constraints:
                    const BoxConstraints(minWidth: 28, minHeight: 28),
                padding: EdgeInsets.zero,
                style: IconButton.styleFrom(
                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _HeaderCell extends StatelessWidget {
  final String label;

  const _HeaderCell(this.label);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 8),
      child: Text(label, style: CodeOpsTypography.labelMedium),
    );
  }
}

class _DataCell extends StatelessWidget {
  final String? text;
  final Widget? child;
  final bool mono;

  const _DataCell({this.text, this.child, this.mono = false});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 8),
      child: child ??
          Text(
            text ?? '\u2014',
            style: mono
                ? CodeOpsTypography.code.copyWith(fontSize: 11)
                : CodeOpsTypography.bodySmall,
            overflow: TextOverflow.ellipsis,
          ),
    );
  }
}
