// Tests for ConfigPreviewPanel widget.
//
// Verifies empty state, config content rendering, metadata header,
// copy button, and download button presence.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:codeops/models/registry_enums.dart';
import 'package:codeops/models/registry_models.dart';
import 'package:codeops/widgets/registry/config_preview_panel.dart';

const _sampleConfig = ConfigTemplateResponse(
  id: 'cfg-1',
  serviceId: 'svc-1',
  serviceName: 'CodeOps Server',
  templateType: ConfigTemplateType.dockerCompose,
  environment: 'dev',
  contentText: 'version: "3.8"\nservices:\n  app:\n    image: codeops:latest',
  isAutoGenerated: true,
  generatedFrom: 'registry',
  version: 2,
);

void _setWideViewport(WidgetTester tester) {
  tester.view.physicalSize = const Size(1600, 900);
  tester.view.devicePixelRatio = 1.0;
}

Widget _buildPanel({ConfigTemplateResponse? config}) {
  return ProviderScope(
    child: MaterialApp(
      home: Scaffold(
        body: SingleChildScrollView(
          child: ConfigPreviewPanel(config: config),
        ),
      ),
    ),
  );
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('ConfigPreviewPanel', () {
    testWidgets('renders empty state when no config', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPanel());
      await tester.pumpAndSettle();

      expect(
        find.text('Select a config type and click Generate'),
        findsOneWidget,
      );
    });

    testWidgets('renders config content', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPanel(config: _sampleConfig));
      await tester.pumpAndSettle();

      // The ScribeEditor should render (CodeEditor is the underlying widget)
      expect(find.text('Docker Compose'), findsOneWidget);
    });

    testWidgets('renders header with metadata', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPanel(config: _sampleConfig));
      await tester.pumpAndSettle();

      expect(find.text('dev'), findsOneWidget);
      expect(find.text('v2'), findsOneWidget);
      expect(find.text('auto'), findsOneWidget);
    });

    testWidgets('copy button present', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPanel(config: _sampleConfig));
      await tester.pumpAndSettle();

      expect(find.byTooltip('Copy to clipboard'), findsOneWidget);
    });

    testWidgets('download button present', (tester) async {
      _setWideViewport(tester);
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);
      await tester.pumpWidget(_buildPanel(config: _sampleConfig));
      await tester.pumpAndSettle();

      expect(find.byTooltip('Download file'), findsOneWidget);
    });
  });
}
